# Generated by Django 3.1.2 on 2020-12-12 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion_Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('accept_sms', models.BooleanField()),
                ('accept_email', models.BooleanField()),
                ('user_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
